---
title: "County Level Corona Maps"
author: "Charles Baird"
date: "7/25/2020"
output: pdf_document
---

```{r}
library(maps)
library(magrittr)
library(socviz)
library(plyr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(censusapi)

# Add my key for Census API
Sys.setenv(CENSUS_KEY="497db0a71281d3182fae2061b21010cf173b963d")
Sys.getenv("CENSUS_KEY")

# Get County level population
POP <- getCensus(name = "pep/population", vars = c("POP"), region = "county:*", vintage = 2019)

# Our map data uses "id" for county level FIPS
# So we make our population data frame that way
censPop19 <- cbind.data.frame("id" = paste(POP$state, POP$county, sep = ""), POP = POP$POP, stringsAsFactors = F)

# County level map data
map <- county_map

# "Wade Hampton Census Area, Alaska" (geo code AK270, 
# FIPS code 02270) was renamed and recoded as "Kusilvak 
# Census Area" (AK158, 02158) effective July 1, 2015.
map[map$id == "02270", ]$id <- "02158"

# Lakota County (FIPS 46102) as of May 1st, 2015.
# Action: replace FIPS code 46102 with the old code 46113.
map[map$id == "46113", ]$id <- "46102"

# Virginia, 2013: Bedford (independent) city (FIPS 51515) 
# was changed to town status and added to Bedford County
# (FIPS 51019) effective July 1st, 2013.
map[map$id == "51515", ]$id <- "51019"

# Then we can join that to the map data
map_withPop <- left_join(map, censPop19, by = "id")

# Now we fetch confirmed cases of Covid 19
# Use "id" for county level FIPS
cov19 <- read.csv("https://static.usafacts.org/public/data/covid-19/covid_confirmed_usafacts.csv")
names(cov19)[names(cov19) == "ï..countyFIPS"] <- "id"

# Remove statewide unallocated and NYC unallocated/probable
# Remove Grand Princess Cruise Ship
cov19 <- cov19[as.integer(cov19$id) > 1000 &
                 cov19$id != "6000",]
```

```{r}
# Change Wade Hampton

cov19[as.integer(cov19$id) == 2270, ]$id <- "02158"

## covStat contains:
#   new: New cases in past 7 days
#   old: New cases in 7 days before new
#   month: New cases in past 28 days

covStat <- data.frame(new = cov19[,ncol(cov19)] -
                   cov19[,ncol(cov19) - 7],
                 old = cov19[,ncol(cov19) - 7] -
                   cov19[,ncol(cov19) - 14],
                 month = cov19[,ncol(cov19)] -
                   cov19[,ncol(cov19) - 28])

covStat <- apply(covStat, 2, function(x){
  ifelse(x < 0, 0, x)
})

adjRate <- apply(covStat, 1, function(x){
  ifelse(x[2] == 0, (2 * x[1]) / (x[3] + 1), x[1] / x[2])
})

adjRate <- ifelse(adjRate < 1/4, 1/4, ifelse(adjRate > 4, 4, adjRate))

# Build a data frame with the stat we will use to color
#   the counties (wkRate) the ratio of new cases in the
#   past seven days to new cases in the seven previous
df_rate <- cbind.data.frame(cov19[,1:4], covStat,
                            wkRate = adjRate)

# We will join our data by "id" (FIPS)
# Get them on the same page
map_withPop$id <- as.integer(map_withPop$id)
df_rate$id <- as.integer(df_rate$id)

map_FULL <- left_join(map_withPop, df_rate, by = "id")
```

```{r}
## This function makes a ggplot map with counties colored
#   by the ratio of new cases this week over last week
#   @param df: data frame with map and data
#   @param i: increment to color map by
#       1 i = 1 infection over past month per 1k people
#       NA for all values below inc level
#   @return: colored map

plotCov <- function(df, i){
  inc <- (as.numeric(df[,14])/as.numeric(df[,8])) > (i/1000)
  
  p0 <- ggplot(data = df,
               mapping = aes(x = long, y = lat,
                             fill = ifelse(inc, log(wkRate),
                                           NA),
                             group = group)) +
    ggtitle(paste(na.omit(df$State),":","Over", i,
                  "per 1000 infected in past 28 days", "\n",
                  "(Counties grayed out when below
                  threshold)"))
  
  p1 <- p0 + geom_polygon(color = "gray90",
                          size = 0.01) + coord_equal()
  
  p2 <- p1 +
    scale_fill_distiller(palette = "Spectral",
                         breaks = c(log(1/4), log(1/2),
                                    log(1), log(2), log(4)),
                         labels = c(expression(over("x","4+"),
                                               over("x", "2"),
                                               "1x", "2x",
                                               "4x")),
                         limits = c(log(1/4), log(4)))
  
  ret = p2 + labs(fill = "Weekly Rate of Increase: ") +
    theme_map() +
    theme(legend.position = "bottom", legend.text =
            element_text(vjust = .5), legend.title =
            element_text(vjust = .25))
  
  return(ret)
}
```

```{r}
## This generates a map with plotCov for given data at
#   every infection level graduated at 1 per 1k infected
#   in the last 4 weeks
#
#   @param df: data frame with map and data
#   @return: colored map

generState <- function(df){
  j = 0
  
  inc <- df[,14] / as.numeric(df[,8])

  vec <- c()
  index = 1
  
  # Produces a vector which indexes when a map is
  #   actually different than the previous. So, in case
  #   one county is blown up, you don't generate a bunch
  #   of identical intermediate plots
  while(sum(inc>(j*.001)) > 0){
    j = j + 1
    if(sum(inc>(j*.001)) != sum(inc>((j-1)*.001))){
      vec <- c(vec, (j-1))
      index = index + 1
    }
  }
  
  # This exports the images we will convert to GIFs with
  #   ffmpeg afterward as well as returns the maps
  return(lapply(vec, function(x){
    ggsave(paste0(df$State[which(!is.na(df$State))[1]], which(vec == x), ".jpg"),
           plotCov(df, x))
    plotCov(df, x)
  })
  )
}

generState(map_FULL)
```
